Asp_net_timetable/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp_net_timetable.Controllers
{
    public class AccessController : Controller
    {
        // GET: Access
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Admin()
        {
            return View();
        }
    }
}

Asp_net_timetable/Controllers/GroupMSController.cs
using Asp_net_timetable.Models;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Asp_net_timetable.Controllers
{
    public class GroupMSController : Controller
    {
        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "RcCQaBiJfpx6Nx2UFzCN4gFmdvwI5fkue3BMFMPL",
            BasePath = "https://asp-net-timetable-default-rtdb.europe-west1.firebasedatabase.app"
        };

        IFirebaseClient infa;
        // GET: Login

        public ActionResult Index()
        {
            infa = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = infa.Get("GroupMS_Нижняя_Первая/");
            //FirebaseResponse response = infa.Get(data.dayOfWeek + " / " + data.time);
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<GroupMSModel>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<GroupMSModel>(((JProperty)item).Value.ToString()));
            }
            list.Reverse();
            return View(list);
        }       

        public ActionResult IndexTop()
        {
            infa = new FireSharp.FirebaseClient(config);
            //var link = groupMS;
            FirebaseResponse response = infa.Get("GroupMS_Верхняя_Первая/");
            //FirebaseResponse response = infa.Get(data.dayOfWeek + " / " + data.time);
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<GroupMSModel>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<GroupMSModel>(((JProperty)item).Value.ToString()));
            }
            list.Reverse();
            return View(list);
        }

        public ActionResult Index_Second()
        {
            infa = new FireSharp.FirebaseClient(config);
            //var link = groupMS;
            FirebaseResponse response = infa.Get("GroupMS_Нижняя_Вторая/");
            //FirebaseResponse response = infa.Get(data.dayOfWeek + " / " + data.time);
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<GroupMSModel>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<GroupMSModel>(((JProperty)item).Value.ToString()));
            }
            list.Reverse();
            return View(list);
        }

        public ActionResult Index_Top_Second()
        {
            infa = new FireSharp.FirebaseClient(config);
            //var link = groupMS;
            FirebaseResponse response = infa.Get("GroupMS_Верхняя_Вторая/");
            //FirebaseResponse response = infa.Get(data.dayOfWeek + " / " + data.time);
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<GroupMSModel>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<GroupMSModel>(((JProperty)item).Value.ToString()));
            }
            list.Reverse();
            return View(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(GroupMSModel groupMS)
        {
            try
            {
                AddDataToFirebase(groupMS);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View();
        }

        private void AddDataToFirebase(GroupMSModel groupMS)
        {
            infa = new FireSharp.FirebaseClient(config);
            var data = groupMS;
            int day_id = 0, time_id = 0;
            string link;

            switch (Convert.ToString(data.dayOfWeek))
            {
                case "Понедельник":
                    day_id = 6;
                    break;
                case "Вторник":
                    day_id = 5;
                    break;
                case "Среда":
                    day_id = 4;
                    break;
                case "Четверг":
                    day_id = 3;
                    break;
                case "Пятница":
                    day_id = 2;
                    break;
                case "Суббота":
                    day_id = 1;
                    break;
            }

            switch (Convert.ToString(data.time))
            {
                case "9:00 - 10:20":
                    time_id = 6;
                    break;
                case "10:40 - 12:00":
                    time_id = 5;
                    break;
                case "12:10 - 13:30":
                    time_id = 4;
                    break;
                case "14:00 - 15:20":
                    time_id = 3;
                    break;
                default:
                    time_id = 2;
                    break;
            }

            data.id = data.tipeOfWeek + "_" + day_id + "_" + time_id + "_" + data.subgroup;

            if (Convert.ToString(data.tipeOfWeek) == "Нижняя")
            {
                if (Convert.ToString(data.subgroup) == "Первая")
                    link = "GroupMS_Нижняя_Первая/";
                else
                    link = "GroupMS_Нижняя_Вторая/";
            }
            else
            {
                if (Convert.ToString(data.subgroup) == "Первая")
                    link = "GroupMS_Верхняя_Первая/";
                else
                    link = "GroupMS_Верхняя_Вторая/";
            }                    

            PushResponse response = infa.Push(link + data.id, data);
            //data.id = response.Result.name;

            //добавляет всю инфу из класса, название раздела будет понедельник
            SetResponse setResponse = infa.Set(link + data.id, data);
        }

        public ActionResult GeneratePdf()
        {
            return new Rotativa.ActionAsPdf("Index");
        }

        public ActionResult GeneratePdfTop()
        {
            return new Rotativa.ActionAsPdf("IndexTop");
        }

        public ActionResult GeneratePdfSecond()
        {
            return new Rotativa.ActionAsPdf("Index_Second");
        }

        public ActionResult GeneratePdfTopSecond()
        {
            return new Rotativa.ActionAsPdf("Index_Top_Second");
        }
    }
}

Asp_net_timetable/Views/Access/Admin.cshtml
@{
    ViewBag.Title = "Администратор";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="display-4"><br></h4>

<div class="text-center">
    <div class="bs-component">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                @Html.ActionLink("Пользователь", "Index", "Access")
            </li>
            <li class="nav-item active">
                @Html.ActionLink("Администратор", "Admin", "Access")
            </li>
        </ul>
    </div>
</div>

<h4 class="display-4"></h4>

<div class="card mb-3" style="max-width: 1000px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="https://sun9-30.userapi.com/impg/QJpZtqtzfwMExNyMeG1EFjwuL4z44AeJF-9-3A/zE8VCEaqFq8.jpg?size=554x544&quality=96&sign=1d46d735f1c5aef403f6e04d4db43ee2&type=album" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><b>Администратор</b></h5>
                <p class="card-text">Возможности: <br> - Просматривать расписание <br> - Скачивать любое расписание в формате .pdf<br> - Редактировать расписание </p>
                <br><br><button type="button" class="btn btn-light">@Html.ActionLink("Изменить расписание", "Create", "GroupMS")</button>

                @*<p class="card-text"><small class="text-muted">Если хотели расширить свои права, перейдите в режим "Администратора"</small></p>*@
            </div>
        </div>
    </div>
</div>

Asp_net_timetable/Views/Access/Index.cshtml
@{
    ViewBag.Title = "Пользователь";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="display-4"><br></h4>

<div class="text-center">
    @*<h4 class="display-4">Режим "Пользователь"</h4>*@
    <div class="bs-component">
        <ul class="nav nav-tabs">
            <li class="nav-item active">
                @Html.ActionLink("Пользователь", "Index", "Access")
            </li>
            <li class="nav-item">
                @Html.ActionLink("Администратор", "Admin", "Access")
            </li>
        </ul>
    </div>
</div>

<h4 class="display-4"></h4>

<div class="card mb-3" style="max-width: 1000px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="https://sun9-69.userapi.com/impf/ifIxgyBQAah97WcyX1uFzj8Z9QakogCtSKOU-Q/Y8FyY5fi1z4.jpg?size=335x347&quality=96&sign=1eddbfa822c37a196497333011470612&type=album" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><b>Пользователь</b></h5>
                <p class="card-text">Возможности: <br> - Просматривать расписание <br> - Скачивать любое расписание в формате .pdf</p>

                <p class="card-text"><small class="text-muted">Если хотели расширить свои права, перейдите в режим "Администратора"</small></p>
            </div>
        </div>
    </div>
</div>